### ISSUE TITLE
Target curve not found?

### ISSUE THREAD

**Issue by jerrellmardis** [ObsessiveCompulsiveAudiophile/A1EvoAcoustica#13]
I'm getting the following error when I start optimizations in REW V6.40 Beta 78
```
[WARNING] ⚠ Target curve not found. Please upload your preferred target curve under "REW/EQ/Target settings/House curve".
```
I've confirmed that the target curve is set in REW/EQ/Target settings/House curve (see image).

![Image](https://github.com/user-attachments/assets/ace35c27-32c0-41bd-aff0-951daf264cb9)

**Comment by ObsessiveCompulsiveAudiophile** [comment]
This is due to recent change in REW Beta 78 in house curve API endpoint from json to text string. Someone reported problem was fixed if target curve is not in a folder containing non-English letters but needs to be double checked.

**Comment by jerrellmardis** [comment]
I changed the name of the folder containing the house curves to "Targets" but am still experiencing the issue. I'm on a Mac btw.

**Comment by WinkelB** [comment]
you can download the Version 77 here [https://www.roomeqwizard.com/installers/](https://www.roomeqwizard.com/installers/)

This worked for me
